import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Adds the customer/admin-facing order identifiers: a UUID (`publicId`)
 * and a short human-readable code (`orderCode`), generated by the app at
 * placement time going forward. Existing dev/test rows are backfilled
 * here so the NOT NULL / UNIQUE constraints can be added in the same
 * migration; `gen_random_uuid()` is native to Postgres 13+, no extension
 * needed.
 */
export class AddOrderPublicIdAndCode1758521600000 implements MigrationInterface {
  name = 'AddOrderPublicIdAndCode1758521600000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "orders"."orders" ADD COLUMN "publicId" uuid`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" ADD COLUMN "orderCode" character varying(20)`);

    await queryRunner.query(`UPDATE "orders"."orders" SET "publicId" = gen_random_uuid() WHERE "publicId" IS NULL`);
    await queryRunner.query(`
      UPDATE "orders"."orders"
      SET "orderCode" = 'SC-' || upper(substr(md5(random()::text || id::text), 1, 8))
      WHERE "orderCode" IS NULL
    `);

    await queryRunner.query(`ALTER TABLE "orders"."orders" ALTER COLUMN "publicId" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" ALTER COLUMN "orderCode" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" ADD CONSTRAINT "UQ_orders_publicId" UNIQUE ("publicId")`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" ADD CONSTRAINT "UQ_orders_orderCode" UNIQUE ("orderCode")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "orders"."orders" DROP CONSTRAINT "UQ_orders_orderCode"`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" DROP CONSTRAINT "UQ_orders_publicId"`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" DROP COLUMN "orderCode"`);
    await queryRunner.query(`ALTER TABLE "orders"."orders" DROP COLUMN "publicId"`);
  }
}
